name: Main Branch CI Image Build
on:
  push:
    branches: main
jobs:
  build-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      GHCR_PAT: ${{secrets.GHCR_PAT}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/digiblink/bullseye-nginx-php5-fpm
          tags: |
            type=sha,prefix=
          flavor: |
            latest=true
            prefix=
            suffix=
          labels: |
            org.opencontainers.image.vendor=digiBlink
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
